#!/bin/bash

echo "🔄 RESETTING APP STATE"
echo "======================"
echo ""
echo "This will clear all UserDefaults so you can test auth flow again."
echo ""
echo "Run this, then delete and reinstall the app on your iPhone."
echo ""
echo "Keys to clear:"
echo "  • depresso_user_id"
echo "  • hasSeenWelcome"  
echo "  • hasCompletedOnboarding"
echo ""
echo "After reset:"
echo "  1. Delete app from iPhone"
echo "  2. Run from Xcode again"
echo "  3. You'll see authentication screen"
echo "  4. Skip → Creates guest account"
echo "  5. Should proceed to main app"
echo ""
echo "To manually check UserDefaults:"
echo "  defaults read com.yourcompany.Depresso"
echo ""
echo "✅ Done! Now delete app from iPhone and run from Xcode."
